# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexico',
            name='lista',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=None, max_length=66, size=6),
        ),
    ]
